# Generated by Django 2.1 on 2019-05-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='about',
            new_name='aboutme',
        ),
    ]
