# Generated by Django 2.1 on 2019-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
